[pytest]
minversion = 8.0
python_files = test_*.py
pythonpath = src
markers =
    slow: long-running tests
    fixture: tests that require binary fixture files
    performance: performance-sensitive tests
xfail_strict = true
testpaths = src

addopts = 
    -ra 
    --strict-config 
    --strict-markers 
    --basetemp=.pytest_tmp 
    -n auto 
    --dist loadscope 
    --html=reports/test_report.html 
    --self-contained-html

    --cov=oven 
    --cov-report=html:reports/coverage_html 
    --cov-report=term